header = """
/* 
 * Extractous FFI - C Interface
 * 
 * This header file provides a C-compatible interface to the Extractous
 * document extraction library. It is safe for use with Go via cgo or any
 * C-compatible FFI system.
 *
 * License: Apache-2.0
 * Repository: https://github.com/rahulpoonia229/extractous-go
 *
# Includes (only standard C headers)
 * NOTE: All pointers returned by Extractous functions m
# Documentation

ust be freed
 * using the corresponding free functions.
 */
"""


language = "C"     # Generate pure C header (no C++)
style = "both"     # Function prototypes + typedefs
cpp_compat = false # Disable any C++ compatibility


[export]
include = [] # Include all public items
exclude = []
prefix = "" # No custom prefix
item_types = [
  "globals",
  "enums",
  "structs",
  "unions",
  "typedefs",
  "opaque",
  "functions",
  "constants",
]


[layout]
# Must be string values ("true"/"false")
packed = "false"
aligned_n = "0"


# Function configuration
[fn]
rename_args = "None"
args = "auto"
must_use = "auto"
swift_name_macro = ""
no_return = "noreturn"


# Struct configuration
[struct]
rename_fields = "None"
derive_constructor = false
derive_eq = false
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false


# Enum configuration
[enum]
rename_variants = "None"
enum_class = false       # Force C-style enums
prefix_with_name = false


# Constant configuration
[const]
allow_static_const = true
allow_constexpr = false


# Macro expansion configuration
[macro_expansion]
bitflags = false


# Parsing configuration
[parse]
parse_deps = false
include = []
exclude = []
clean = false
extra_bindings = []

[parse.expand]
crates = []
all_features = false
default_features = true
features = []
