name: Build extractous-ffi

on:
  push:
    branches: [ main, testing-workflow ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  RUST_VERSION: "1.90.0"
  GRAALVM_VERSION: "25.0.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux_amd64
            artifact-name: libextractous_ffi.so
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   platform: darwin_amd64
          #   artifact-name: libextractous_ffi.dylib
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   platform: darwin_arm64
          #   artifact-name: libextractous_ffi.dylib
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows_amd64
            artifact-name: extractous_ffi.dll

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Cache extractous build to avoid rebuilding unchanged dependencies
      - name: Cache extractous build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            extractous-build
          key: ${{ runner.os }}-${{ matrix.target }}-extractous-${{ hashFiles('**/Cargo.lock', 'extractous-version.txt') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libssl-dev \
            zip \
            unzip \
            wget \
            curl \
            ldd

      # - name: Install system dependencies (macOS)
      #   if: startsWith(matrix.os, 'macos')
      #   run: |
      #     brew install wget

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1.4.1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.TOKEN }}
          native-image-job-reports: 'true'

      - name: Verify GraalVM installation
        run: |
          java -version
          native-image --version

      - name: Install cbindgen & extractous
        run: cargo install cbindgen, extractous

      - name: Build FFI library
        shell: bash
        run: |
          BUILD_START_TIME=$(date +%s)

          # Build the FFI library
          cargo build --release --target ${{ matrix.target }}

          BUILD_END_TIME=$(date +%s)
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "Build completed successfully in ${BUILD_DURATION} seconds"

          # Show the directory structure
          echo "General file structure"
          ls -lhR ./

          echo "Release folder structure"
          ls -lhR target/${{ matrix.target }}/release/


      - name: Prepare distribution
        shell: bash
        run: |
          mkdir -p dist/${{ matrix.platform }}
          
          # Copy the built FFI library
          cp target/${{ matrix.target }}/release/${{ matrix.artifact-name }} dist/${{ matrix.platform }}/
          
          # Copy native dependencies
          if [ -d "native-deps/${{ matrix.platform }}" ]; then
            cp -r native-deps/${{ matrix.platform }}/* dist/${{ matrix.platform }}/
          fi
          
          # Copy generated header
          if [ -f "include/extractous.h" ]; then
            cp include/extractous.h dist/${{ matrix.platform }}/
          fi
          
          # Create a simple test to verify library loading
          echo "Creating verification script..."
          if [[ "${{ matrix.os }}" == "windows-2019" ]]; then
            cat > dist/${{ matrix.platform }}/verify.bat << 'EOF'
          @echo off
          echo Verifying extractous_ffi.dll...
          where extractous_ffi.dll
          if %ERRORLEVEL% NEQ 0 (
              echo ERROR: extractous_ffi.dll not found
              exit /b 1
          )
          echo SUCCESS: Library files present
          EOF
          else
            cat > dist/${{ matrix.platform }}/verify.sh << 'EOF'
          #!/bin/bash
          echo "Verifying library files..."
          if [[ "$OSTYPE" == "darwin"* ]]; then
              LIB_FILE="libextractous_ffi.dylib"
          else
              LIB_FILE="libextractous_ffi.so"
          fi
          
          if [ ! -f "$LIB_FILE" ]; then
              echo "ERROR: $LIB_FILE not found"
              exit 1
          fi
          
          if command -v ldd >/dev/null 2>&1; then
              echo "Library dependencies:"
              ldd "$LIB_FILE" || true
          elif command -v otool >/dev/null 2>&1; then
              echo "Library dependencies:"
              otool -L "$LIB_FILE" || true
          fi
          
          echo "SUCCESS: Library files present"
          EOF
            chmod +x dist/${{ matrix.platform }}/verify.sh
          fi

      - name: Run verification
        shell: bash
        working-directory: dist/${{ matrix.platform }}
        run: |
          if [[ "${{ matrix.os }}" == "windows-2019" ]]; then
            ./verify.bat
          else
            ./verify.sh
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extractous-ffi-${{ matrix.platform }}
          path: dist/${{ matrix.platform }}
