name: Build extractous-ffi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  RUST_VERSION: "1.90.0"
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux_amd64
            target: x86_64-unknown-linux-gnu
            lib_ext: so
            os_name: Linux
            archive_ext: tar.gz
            
          - os: windows-latest
            platform: windows_amd64
            target: x86_64-pc-windows-msvc
            lib_ext: dll
            os_name: Windows
            archive_ext: zip
            
          # - os: macos-13
          #   platform: darwin_amd64
          #   target: x86_64-apple-darwin
          #   lib_ext: dylib
          #   os_name: macOS
          #   archive_ext: tar.gz
            
          # - os: macos-latest
          #   platform: darwin_arm64
          #   target: aarch64-apple-darwin
          #   lib_ext: dylib
          #   os_name: macOS
          #   archive_ext: tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Platform-specific Setup
      - name: Setup Visual Studio (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install Xcode Command Line Tools (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install 2>/dev/null || true

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'false'
          components: 'native-image'
          set-java-home: 'true'

      - name: Verify GraalVM installation
        shell: bash
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          java -version
          native-image --version

      # Rust Toolchain
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          workspaces: "./ffi -> target"
          cache-on-failure: true

      # For Unix-based systems (Linux/macOS)
      - name: Build FFI library (Unix)
        if: runner.os != 'Windows'
        working-directory: ./ffi
        shell: bash
        run: |
          BUILD_START=$(date +%s)
          cargo build --release --target ${{ matrix.target }} --quiet
          BUILD_END=$(date +%s)
          BUILD_TIME=$((BUILD_END - BUILD_START))
          echo "Build completed in ${BUILD_TIME}s"
          echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV
        env:
          RUST_BACKTRACE: 1

      # For Windows
      - name: Build FFI library (Windows)
        if: runner.os == 'Windows'
        working-directory: ./ffi
        shell: pwsh
        run: |
          $BUILD_START = (Get-Date).ToUniversalTime().ToUnixTimeSeconds()
          cargo build --release --target ${{ matrix.target }} --quiet
          $BUILD_END = (Get-Date).ToUniversalTime().ToUnixTimeSeconds()
          $BUILD_TIME = $BUILD_END - $BUILD_START
          Write-Host "Build completed in $BUILD_TIME seconds"
          "BUILD_TIME=$BUILD_TIME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        env:
          RUST_BACKTRACE: 1


      # Verify Build
      - name: Verify build outputs
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/verify-build.sh
          ./.github/workflows/scripts/verify-build.sh ${{ matrix.target }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      # Collect Dependencies
      - name: Collect dependencies
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/collect-dependencies.sh
          ./.github/workflows/scripts/collect-dependencies.sh ${{ matrix.platform }} ${{ matrix.target }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      # Optimize Libraries
      - name: Strip debug symbols (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "${{ matrix.os_name }}" = "Linux" ]; then
            find dist/${{ matrix.platform }}/lib -name "*.so" -exec strip --strip-debug {} \;
          elif [ "${{ matrix.os_name }}" = "macOS" ]; then
            find dist/${{ matrix.platform }}/lib -name "*.dylib" -exec strip -x {} \;
          fi
          echo "Optimized size: $(du -sh dist/${{ matrix.platform }}/lib/ | cut -f1)"

      # Verify Distribution
      - name: Verify distribution
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/verify-distribution.sh
          ./.github/workflows/scripts/verify-distribution.sh ${{ matrix.platform }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      # Create Archive
      - name: Create distribution archive
        shell: bash
        run: |
          cd dist/${{ matrix.platform }}
          
          if [ "${{ matrix.os_name }}" = "Windows" ]; then
            7z a ../../extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }} lib/ include/
          else
            tar -czf ../../extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }} lib/ include/
          fi
          
          cd ../..
          ls -lh extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}

      # Generate Checksums
      - name: Generate checksums
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            certutil -hashfile extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }} SHA256 > extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}.sha256
          else
            shasum -a 256 extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }} > extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}.sha256
          fi
          cat extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}.sha256

      # Upload Artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extractous-ffi-${{ matrix.platform }}
          path: |
            extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}
            extractous-ffi-${{ matrix.platform }}.${{ matrix.archive_ext }}.sha256
          retention-days: 3