name: Build

on:
  push:
    branches: [ main,fix_tika_deps ]
    paths:
      - 'ffi/**'
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
      - '.github/workflows/scripts/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    outputs:
      run_id:
        description: "The run ID of this workflow"
        value: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: "1.90.0"
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'quay.io/pypa/manylinux_2_28_x86_64' || '' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux_amd64
            target: x86_64-unknown-linux-gnu
            lib_ext: so
            os_name: Linux
            archive_ext: tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup GraalVM inside container (Linux)
        if: runner.os == 'Linux'
        run: |
          # Install dependencies required by sdkman
          yum install -y zip unzip

          # Install sdkman in non-interactive mode
          curl -s "https://get.sdkman.io" | sh -s -- -y

          # Source the init script using the correct $HOME variable
          # The CI environment's home directory is /github/home, not /root
          source "$HOME/.sdkman/bin/sdkman-init.sh"

          # Install and use the correct GraalVM version
          sdk install java 23.0.1-graalce
          sdk use java 23.0.1-graalce

          # Set environment variables for subsequent steps
          echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

          # Verify installation
          java --version
          native-image --version

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v2-rust"
          shared-key: ${{ matrix.target }}
          workspaces: "./ffi"
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Cache GraalVM native build outputs
        id: cache-graalvm
        uses: actions/cache@v4
        with:
          path: |
            ffi/target/${{ matrix.target }}/release/build/extractous-*/out
          key: graalvm-v5-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('ffi/Cargo.lock', 'ffi/Cargo.toml', 'ffi/build.rs') }}
          restore-keys: |
            graalvm-v5-${{ runner.os }}-${{ matrix.target }}-

      - name: Cache status
        shell: bash
        run: |
          if [ "${{ steps.cache-graalvm.outputs.cache-hit }}" = "true" ]; then
            echo "GraalVM cache HIT — skipping full native image rebuild"
          else
            echo "GraalVM cache MISS — full native image compilation required"
          fi

      - name: Build FFI library
        working-directory: ./ffi
        shell: bash
        run: |
          start=$(date +%s)
          export GRADLE_OPTS="-PnativeImageArgs=-H:NativeLinkerOption=-ldl -H:NativeLinkerOption=-lpthread -H:NativeLinkerOption=-lrt"
          cargo build --release --target ${{ matrix.target }}
          end=$(date +%s)
          echo "Build completed in $((end - start))s"
        env:
          RUST_BACKTRACE: 1

      - name: Verify build outputs
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/verify-build.sh
          ./.github/workflows/scripts/verify-build.sh ${{ matrix.target }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      - name: Collect dependencies
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/collect-dependencies.sh
          ./.github/workflows/scripts/collect-dependencies.sh ${{ matrix.platform }} ${{ matrix.target }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      - name: Strip debug symbols
        shell: bash
        run: |
          find dist/${{ matrix.platform }}/lib -name "*.so" -exec strip --strip-debug {} \;
          echo "Optimized library size:"
          du -sh dist/${{ matrix.platform }}/lib/ || true

      - name: Verify distribution
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/verify-distribution.sh
          ./.github/workflows/scripts/verify-distribution.sh ${{ matrix.platform }} ${{ matrix.lib_ext }} ${{ matrix.os_name }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extractous-ffi-${{ matrix.platform }}
          path: dist/${{ matrix.platform }}
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 7 }}
          compression-level: 9
          if-no-files-found: error